# Generated by Django 4.1.4 on 2023-01-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
