# Generated by Django 4.1.4 on 2023-01-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='image_data',
        ),
        migrations.RenameField(
            model_name='image_data',
            old_name='image',
            new_name='pimage',
        ),
        migrations.RenameField(
            model_name='image_data',
            old_name='name',
            new_name='pname',
        ),
    ]
