# Generated by Django 4.1.4 on 2023-01-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_rename_images_image_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_data',
        ),
    ]
