# Generated by Django 4.1.4 on 2023-01-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_delete_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pimage', models.FileField(default=0, upload_to='')),
            ],
        ),
    ]
