# Generated by Django 4.1.4 on 2023-03-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Student',
        ),
    ]
